---
# tasks file for redis
- name: apt-get update
  apt:
    update-cache: yes

- name: Insert a line at the end of a file.
  lineinfile:
    path: /etc/profile
    line: export JAVA_HOME=$(dirname $(dirname $(readlink $(readlink $(which javac)))))

- name: Add another bin dir 
  lineinfile:
    path: /etc/profile
    line: export PATH=$PATH:$JAVA_HOME/bin

- name: Add another bin dir
  lineinfile:
    path: /etc/profile
    line: export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar
    
- name: include deb.yml
  include: deb.yml
  when: ansible_distribution == "Ubuntu"

- name: include yum.yml
  include: yum.yml
  when: ansible_distribution == "CentOS"

- name: Start Elasticsearch.
  service:
    name: elasticsearch
    state: "{{ elasticsearch_service_state }}"
    enabled: "{{ elasticsearch_service_enabled }}"




                                                              21,3          33%


