---
- name: Install Java 8 CentOS
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: import key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  
- copy:
    src: elasticsearch.repo
    dest: '/etc/yum.repo.d/elasticsearch.repo'
    mode: 0644

- name: install elasticsearch
  yum:
    name: elasticsearch
    state: present
  
